"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.15.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from a local .env file (never commit this file).
load_dotenv(BASE_DIR / '.env')


def _env_bool(name, default=False):
    return os.environ.get(name, str(default)).strip().lower() in {'1', 'true', 'yes', 'on'}


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    'DJANGO_SECRET_KEY',
    'django-insecure-z^$c58_a5^ii-)-cq&fgyytse$-9z=%oad0q$1tfcp_b2hs)@_',
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = _env_bool('DJANGO_DEBUG', default=True)

# Allow access from the smart board / other devices on the school LAN.
ALLOWED_HOSTS = os.environ.get('DJANGO_ALLOWED_HOSTS', '*').split(',')

# Trust LAN origins for CSRF when serving the board to other devices.
CSRF_TRUSTED_ORIGINS = [
    o for o in os.environ.get('DJANGO_CSRF_TRUSTED_ORIGINS', '').split(',') if o
]

# ---------------------------------------------------------------------------
# Groq AI configuration (https://console.groq.com/docs/overview)
# ---------------------------------------------------------------------------
GROQ_API_KEY = os.environ.get('GROQ_API_KEY', '')
# Optional pool of extra keys for automatic failover on rate limits (429).
# Comma-separated in GROQ_API_KEYS; the pool = GROQ_API_KEY + those (deduped).
_extra_keys = os.environ.get('GROQ_API_KEYS', '')
GROQ_API_KEYS = []
for _k in [GROQ_API_KEY] + _extra_keys.split(','):
    _k = _k.strip()
    if _k and _k not in GROQ_API_KEYS:
        GROQ_API_KEYS.append(_k)
GROQ_BASE_URL = os.environ.get('GROQ_BASE_URL', 'https://api.groq.com/openai/v1')
# Chat model used for explanations / quizzes / translation / activities.
GROQ_LLM_MODEL = os.environ.get('GROQ_LLM_MODEL', 'qwen/qwen3-32b')
# Qwen3 is a reasoning model; "none" disables its <think> step so JSON mode stays
# clean and fast. Ignored for non-qwen models.
GROQ_REASONING_EFFORT = os.environ.get('GROQ_REASONING_EFFORT', 'none')
# Speech-to-text model used to transcribe Hinglish classroom audio.
GROQ_STT_MODEL = os.environ.get('GROQ_STT_MODEL', 'whisper-large-v3-turbo')
# Text-to-speech: Groq's Orpheus neural voice (natural, expressive). Requires a
# one-time terms acceptance by the org admin in the Groq console. The front-end
# falls back to the browser's built-in voice if this is unavailable.
GROQ_TTS_MODEL = os.environ.get('GROQ_TTS_MODEL', 'canopylabs/orpheus-v1-english')
GROQ_TTS_VOICE = os.environ.get('GROQ_TTS_VOICE', 'diana')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'assistant',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
# Where `collectstatic` gathers files for nginx to serve in production.
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Content-hashed static filenames so the long browser cache never serves a
# stale app.js / styles.css after a deploy (each change gets a new URL).
STORAGES = {
    'default': {'BACKEND': 'django.core.files.storage.FileSystemStorage'},
    'staticfiles': {'BACKEND': 'django.contrib.staticfiles.storage.ManifestStaticFilesStorage'},
}

# Behind nginx (TLS terminates there); trust its forwarded proto so Django
# knows the request is HTTPS for CSRF / secure-cookie purposes.
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
USE_X_FORWARDED_HOST = True

# In production (DEBUG off) harden cookies; harmless over HTTPS.
if not DEBUG:
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
